washingtonpost/wpds-ui-kit

app/pages/index.tsx, package-lock.json, ui/input-password/README.md, ui/input-password/package.json, ui/input-password/src/InputPassword.tsx, ui/input-password/src/index.ts, ui/input-password/src/play.stories.jsx, ui/input-text/package.json, ui/input-text/src/InputText.tsx, ui/kit/package.json, ui/kit/src/index.ts
This PR adds the InputPassword component
=> feat: add InputPassword component

ui/button/src/Button.tsx
When hovering over disabled button background shouldn't change
=> fix: disabled button doesn't change background on hover

ui/input-text/src/InputText.tsx, ui/input-textarea/src/InputTextarea.tsx
This PR removes pointer events from floating labels in inputs. Allowing clicking on the label to focus the input
=> fix: removed pointer events from Label in InputText and InputTextarea

.eslintrc.js, package-lock.json, package.json, ui/eslint-plugin/README.md, ui/eslint-plugin/package.json, ui/eslint-plugin/src/index.js, ui/eslint-plugin/src/rules/theme-colors.js, ui/eslint-plugin/src/rules/theme-colors.test.js, ui/kit/package.json, ui/kit/src/index.ts
This PR adds a new WPDS ESLint plugin with a lint rule that looks for hex strings in objects and suggests replacing them with token values.
```
const ErrorMessageCSS = css({
color: "#ea0017",
}
warning  Use color tokens instead of hex values for maintainability. #ea0017 can be replaced with error
```
=> Prefer token values to hex colors lint rule

ui/input-shared/src/InputShared.tsx
set text color to "primary" to support inputs in dark mode
=> fix: updates sharedInputStyles text color

ui/input-text/src/InputText.tsx, ui/input-textarea/src/InputTextarea.tsx
- reorder onBlur and onChange args in (input text & input textarea) order to send callbacks to proper places
I able to reproduce the error here https://codesandbox.io/s/wpds-developer-workshop-forked-jw4hoe?file=/Example.js. I noticed it while integrating InputText in the [Tachyons docs site. ](https://github.com/WPMedia/tachyons-css/pull/1/files)
=> fix(input): reorder onBlur and onChange args in order to send callbacks to proper places

ui/alert-banner/src/AlertBanner.tsx, ui/checkbox/src/Checkbox.tsx, ui/input-password/src/InputPassword.tsx, ui/input-text/src/InputText.tsx
This PR changes Icon imports to use named imports allowing for compilation from esm.
Verified to work using Rollup, and Next. This style is properly tree shaken and does not increase package size in Next.
Before:
After:
=> fix: changed icon imports to support ESM compilation

ui/radio-group/src/RadioButton.tsx, ui/radio-group/src/play.stories.jsx
The PR updates RadioButton's layout to allow for multiline labels
=> fix: allow for multiline labels in RadioButtons

build.washingtonpost.com/package.json, package-lock.json, package.json, ui/theme/src/stitches.config.ts
We are using wpds-ui-kit in our rewrite of the elections render engine, but there are some TypeScript incompatibilities with Stitches 1.2.6 (what's currently installed in wpds-ui-kit) and 1.2.8 (the latest version). To get wpds-ui-kit to play nice with our repo, we need to upgrade wpds-ui-kit to 1.2.8.
This PR bumps the version of Stitches as well as TypeScript (since as far as I can tell, the TypeScript version was lower because of TS bugs in Stitches 1.2.6). It requires minor code changes in wpds-theme to reexport stitches-related imports without `*` catch-alls. I'm not sure why that was needed, but there were TypeScript errors before about exporting variables using names from external modules that can't be named ([relevant StackOverflow](https://stackoverflow.com/questions/43900035/ts40 …
=> feat: upgrade to stitches 1.2.8

build.washingtonpost.com/components/Footer.js
quick fix with the misalignment of the 'Edit this page on Github' link when the window is wide. Here is the original:
and here is the fix:
=> fix(docs): EditInGithub alignment bug

README.md, ui/button/src/Button.tsx, ui/checkbox/src/Checkbox.tsx, ui/input-text/src/InputText.tsx, ui/input-textarea/src/InputTextarea.tsx, ui/radio-group/src/RadioButton.tsx, ui/theme/src/stitches.config.ts
BREAKING CHANGE: any element relying on global transition being present will no longer have a transition
This PR removes the global css transition and replaces it where necessary in individual components
=> fix!: remove global transition

docs/CONTRIBUTING.md
we support typescript versions higher than 4.5.5 now.
=> docs: remove typescript note

.github/workflows/interaction-tests.yml
Interaction tests in Github workflows were failing on deployment because storybook testing was being run on the docs site preview alongside the storybook preview. Just added a condition to only allow this test to run on storybook previews.
Tested this workflow in the dummy repo [Site-Engineering-Workflows-Testing-Ground](https://github.com/WPMedia/site-engineering-workflows-testing-ground).
=> Fix(workflows): failing integration test fix

build.washingtonpost.com/docs/foundations/wam.mdx
Typescript doesn't like label as it is not available on an svg. Rather title should be used: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title. With title added, screenreaders will read the title.
=> fix: change label to title as svg does not accept a title and ts will error

build.washingtonpost.com/components/Markdown/Examples/IconSamples.jsx, build.washingtonpost.com/components/Markdown/Examples/LogoSamples.jsx, package-lock.json, package.json
This PR updates the WPDS Assets package and the import code that is copied to the clipboard for assets to favor importing from the top-level package.
=> feat: updated wam version and asset import copy text

ui/input-shared/src/InputShared.tsx, ui/input-text/README.md, ui/input-text/src/InputText.tsx, ui/input-textarea/src/InputTextarea.tsx, ui/theme/src/stitches.config.ts
Input field label autocomplete bug fix
=> fix: input field label autocomplete bug fix

build.washingtonpost.com/components/Layout/Layout.js, build.washingtonpost.com/pages/working-examples/index.tsx, ui/select/src/Select.tsx, ui/select/src/SelectContent.tsx, ui/select/src/SelectItem.tsx, ui/select/src/play.stories.tsx
This PR updates the mobile layout of the docs site to allow Select to be used. When the Select was rendered off-screen it was outside the container element and was un-clickable on mobile.
This should be a special case unique to our layout, offscreen rendering was tested and validated to work in other cases.
In addition, there are some small tweaks to Select to improve its display and TypeScript support
=> feat: allow for use of Select in example form on mobile

.eslintrc.js, build.washingtonpost.com/pages/working-examples/index.tsx, ui/input-text/src/InputText.tsx, ui/input-textarea/src/InputTextarea.tsx
This PR changes the import of React to make API tables work. This is a known issue in `react-typescript-docgen` https://github.com/styleguidist/react-docgen-typescript/issues/323 
WPDS-1293
[WPDS-1293]: https://arcpublishing.atlassian.net/browse/WPDS-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: changed import style to fix missing api table

ui/drawer/src/DrawerScrim.tsx
This PR surfaces `Scrim` props in the `DrawerScrimProps` type
WPDS-1297
[WPDS-1297]: https://arcpublishing.atlassian.net/browse/WPDS-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: included Scrim props in DrawerScrim

package-lock.json, ui/checkbox/src/Checkbox.tsx, ui/checkbox/src/play.stories.jsx
You can now pass in the label as a component child, not just as a label prop.
`<Checkbox label="Checkbox Label"/>`
`<Checkbox>Checkbox Label</Checkbox>`
=> fix: allow passing in checkbox label as child

ui/checkbox/src/Checkbox.tsx, ui/checkbox/src/play.stories.jsx
Make the checkbox align to the top of the multiline text instead of the bottom.
=> feat: align checkbox to top of multiline text

build.washingtonpost.com/docs/components/popover.mdx
Removes unintended padding from inline alert
=> feat: remove padding from inline alert on Popover docs

ui/box/src/play.stories.tsx, ui/button/src/play.stories.tsx, ui/card/src/play.stories.tsx, ui/checkbox/src/play.stories.tsx, ui/container/src/play.stories.tsx
This PR converts the stories for components beginning with  "b" and "c" to TypeScript
WPDS-1310
=> convert stories to .tsx "b" and "c"

build.washingtonpost.com/package.json, package-lock.json
This PR bumps the version of the assets package to include the On the Record, Pin, and eBook icons
=> feat: bump assets package to add new icons

build.washingtonpost.com/next.config.js, package-lock.json
The release is failing due to prettier updating the next.config.file and it not being able to merge the updates.
=> fix: update prettier to fix build

ui/icon/src/icon.tsx, ui/icon/src/play.stories.tsx
Add storybook test for icon fill
=> chore: add storybook test for icon fill

lerna.json
BREAKING CHANGE: Move to 1.0
Manually bumping the Lerna version and including a breaking change commit message to push us to 1.0
SRED-39
=> 1.0 Release

ui/accordion/src/AccordionContent.tsx
[SRED-74](https://arcpublishing.atlassian.net/browse/SRED-74)
Applied the correct font size of wpds token 100 to accordion content
[SRED-74]: https://arcpublishing.atlassian.net/browse/SRED-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: set accordion content font size to token size 100 to match designs

build.washingtonpost.com/docs/resources/accessibility/audio-and-video.mdx, build.washingtonpost.com/docs/resources/accessibility/semantic-html.mdx
Fixed the typos listed in [SRED-107](https://arcpublishing.atlassian.net/jira/software/c/projects/SRED/boards/1185?modal=detail&selectedIssue=SRED-107)
[SRED-107]: https://arcpublishing.atlassian.net/browse/SRED-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: address a couple typos in the a11y build site docs

Makefile, package-lock.json
This PR removes the `--conventional-graduate` flag from the versioning script. It appears that this flag directly conflicts with the `--force-publish` and is preventing all the packages from being versioned together.
=> Lerna versioning

build.washingtonpost.com/package.json, package-lock.json, package.json, ui/accordion/package.json, ui/alert-banner/package.json, ui/carousel/package.json, ui/checkbox/package.json, ui/drawer/package.json, ui/input-password/package.json, ui/input-text/package.json, ui/popover/package.json, ui/select/package.json
Part of [SRED-100](https://arcpublishing.atlassian.net/jira/software/c/projects/SRED/boards/1185?modal=detail&selectedIssue=SRED-100): Upgrade to new wpds-assets version 1.18.0
[SRED-100]: https://arcpublishing.atlassian.net/browse/SRED-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: upgrade wpds-assets to v1.18.0 in root and build.washingtonpost.com

build.washingtonpost.com/docs/resources/accessibility/accessibility-checklist.mdx, build.washingtonpost.com/docs/resources/accessibility/keyboard-accessibility.mdx, package-lock.json
[SRED-164](https://arcpublishing.atlassian.net/browse/SRED-164)
- Our keyDownButtonWrapper was not handling space (" ") keys correctly. I fixed in spectrum and am updating here.
- I also realized we could be providing guidance on how to enable keyboard navigation in Firefox on MacOS.
Check out [the updated docs page](https://wpds-ui-5zwlslec6.preview.now.washingtonpost.com/resources/accessibility/keyboard-accessibility).
[SRED-164]: https://arcpublishing.atlassian.net/browse/SRED-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update keyboard accessibility docs to correct keyDownButtonWrapper and add Firefox guidance

scripts/plopfile.js, templates/component/package.json.hbs
Update template file to use specific version rather than asterisk in deps https://arcpublishing.atlassian.net/browse/SRED-146
=> chore: use exact version rather than wildcard in plop template

build.washingtonpost.com/package.json, package-lock.json
https://github.com/washingtonpost/tachyons-css/releases/tag/v1.7.0
=> chore: bump tachyons to 1.7.0

build.washingtonpost.com/components/Layout/Components/Sidebar.js, build.washingtonpost.com/components/Markdown/Styling.js, build.washingtonpost.com/components/logo.js
Used primary color instead of $accessible on the Sidebar of build.washingtonpost.com.
I'm also interested in updating the contrast on the little "coming soon" labels. Is that doable?
=> fix: improve color contrast on build.washingtonpost.com Sidebar for better accessibility

README.md
It is a good practice to simply state the license and point to the full copy of it.
=> docs: Just to clearly point to the license

ui/tabs/src/TabsList.tsx, ui/tabs/src/TabsRoot.tsx, ui/tabs/src/TabsTrigger.tsx, ui/tabs/src/context.ts, ui/tabs/src/play.stories.tsx
Fix the defaultValue bug in tabs component
=> fix: set active index correctly when default value is passed in

build.washingtonpost.com/package.json, package-lock.json
The logos have the expected #111 now instead of gray. Yay!
=> chore: upgrade wpds-assets to 1.19.2 in build.washingtonpost.com

build.washingtonpost.com/components/Markdown/Components/link.js
Quick fix to add underlines back to links on the build site - following up on this with [SRED-215](https://arcpublishing.atlassian.net/browse/SRED-215) eventually
[SRED-215]: https://arcpublishing.atlassian.net/browse/SRED-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add underline to hyperlinks in build site markdown [SRED-242]

build.washingtonpost.com/components/Contributors.jsx, build.washingtonpost.com/components/Layout/Components/Sidebar.js, build.washingtonpost.com/components/NavigationBar.js, build.washingtonpost.com/components/Typography/link.js, build.washingtonpost.com/pages/index.js
These fixes to the "Welcome" page (and navigation menus) address some feedback we received about the site in the design systems slack.
- Made focus styles consistent (per browser defaults)
- Added proper page landmarks for screen reader accessibility
- Removed alt text that was on purely decorative images
- Hide redundant links to improve both keyboard and screen reader navigation
- Corrected heading order
=> fix: a11y improvements to welcome page and broader page landmarks on build site

ui/tabs/src/TabsList.tsx, ui/tabs/src/TabsRoot.test.tsx, ui/tabs/src/TabsRoot.tsx, ui/tabs/src/TabsTrigger.test.tsx, ui/tabs/src/TabsTrigger.tsx, ui/tabs/src/TabsTriggerContent.test.tsx, ui/tabs/src/TabsTriggerContent.tsx, ui/tabs/src/context.ts, ui/tabs/src/play.stories.tsx
This PR fixes the horizontal shift in Tabs labels when the active tab changes and its text is bolded.
In addition: 
* fixes a bug where the initial tab change would not trigger an indicator animation when the component was uncontrolled. 
* All props are now passed through in the `TabsList` allowing for appearance customization  
SRED-231
=> Tabs visual bugs

README.md, build.washingtonpost.com/README.md, build.washingtonpost.com/docs/components/switch.mdx, build.washingtonpost.com/docs/foundations/wam.mdx
Fixed a few typos or things I found unclear in the READMEs and docs.
=> docs: clean up typos and clarity

ui/input-text/src/InputText.tsx, ui/input-text/src/play.stories.tsx
This PR explicitly types the buttons inside of InputSearch as buttons to prevent their onClick events from being called during a form submission triggered by the enter key.
In addition, the ButtonIcon now surfaces a new `type` prop to set as submit if desired.
=> fix: type InputText buttons as buttons to prevent form submission

build.washingtonpost.com/docs/resources/guides/performance-and-seo.mdx
I added the SEO header back in to this guide. It seems to have been edited out during the last PR. It just needs to have the double hashtag header and horizontal divider added back into the doc.
=> Add SEO header back in to SEO/Perf guide

ui/input-label/src/InputLabel.tsx
We noticed when clicking on input checkboxes in our code examples they did not "tick".
=> fix: Label + Checkbox tick Bug

ui/input-search/src/InputSearchInput.tsx
I'm using the draft version of the `InputSearchInput` for our [mass killings tracker](https://github.com/WPMedia/int-mass-killings-tracker/blob/new-search-box/components/elements/MassKillingsSearch/Search.tsx#L48-L83), and while I've got it working for our use, I want to comment out the logging that snuck into the 1.9.1 release.
=> fix: remove console logging for InputSearchInput

ui/navigation-menu/src/NavigationMenuContent.tsx
This PR fixes a bug where interactive items underneath the NavigationMenu popup were un-clickable 
SRED-345
=> fix: allow clicking of interactive elements below NavigationMenu

build.washingtonpost.com/docs/components/action-menu.mdx, package-lock.json, ui/action-menu/src/ActionMenuCheckboxItem.tsx, ui/action-menu/src/ActionMenuContent.tsx, ui/action-menu/src/ActionMenuIcon.tsx, ui/action-menu/src/ActionMenuItem.tsx, ui/action-menu/src/ActionMenuItemIndicator.tsx, ui/action-menu/src/ActionMenuLabel.tsx, ui/action-menu/src/ActionMenuRadioItem.tsx, ui/action-menu/src/ActionMenuRoot.tsx, ui/action-menu/src/ActionMenuSub.tsx, ui/action-menu/src/ActionMenuSubContent.tsx, ui/action-menu/src/ActionMenuSubTrigger.tsx, ui/action-menu/src/context.tsx, ui/action-menu/src/play.stories.tsx
Simplified context so that docs page works. Got rid of some of the props we were using for the slider behavior since that is backlogged for now, removed RandomUUID which was breaking docs page
=> fix: Simplify Action Menu context

Makefile, package.json
This PR updated the release process to only build the ui packages after versioning and before publishing
SRED-338
=> fix: streamline release process

.github/workflows/latest-release.yml
Husky changed its environment variable names [after v4](https://typicode.github.io/husky/migrating-from-v4.html). Update to [new HUSKY variable](https://typicode.github.io/husky/guide.html#with-env-variables)
=> fix: update Husky env variable name used in CI

package-lock.json, ui/radio-group/src/RadioGroup.tsx, ui/radio-group/src/play.stories.tsx
This PR updates the default behavior of horizontally oriented groups of RadioButtons to wrap if they exceed the width of their container.
It also exposes a new css prop to allow for styling of the RadioButtons containing element
SRED-375
=> fix: allow for RadioButtons in RadioGroup to wrap

build.washingtonpost.com/components/Layout/Components/Sidebar.js
Since we are already rendering two root components by default just updated the category to be the default value of the one accordion in that root. A happy mistake seems like of not using the accordion in a single root but works out in our favor to have them both as a group.
=> fix: set root to be category of each

build.washingtonpost.com/docs/components/carousel.mdx, package-lock.json, package.json, ui/carousel/src/CarouselContent.tsx, ui/carousel/src/CarouselItem.tsx, ui/carousel/src/CarouselRoot.tsx, ui/carousel/src/index.ts, ui/carousel/src/play.stories.jsx, ui/carousel/src/useActiveDescendant.test.tsx, ui/carousel/src/useActiveDescendant.ts, ui/theme/src/token-structure.md
This PR adds a custom hook `useActiveDescendant` that helps to manage keyboard navigation and focus for child interactive elements in the Carousel 
```javascript
const { addDescendant, handleDescendantFocus, contentProps } =
useActiveDescendant();
```
The descendent focus hander is added to the root to monitor the current item with descendant focus
```javascript
<Carousel.Root onDescendantFocus={handleDescendantFocus}>
```
Content props are expanded to pass event handlers and the current `aria-activedescendant` to the content element
```javascript
<Carousel.Content  {...contentProps}>
```
Each CarouselItem must have an id that is then used by its interactive children with the `addDescendant` helper in its ref callback. The interactive child elements must also have an id and have their …
=> feat: add useActiveDescendant hook to simplify child element focus in Carousel

build.washingtonpost.com/docs/components/input-search.mdx
Example is here https://wpds-ui-kit-git-prepopulated-search.preview.now.washingtonpost.com/components/input-search#:~:text=Pre%20populated%20results
=> docs: example of prepopulated search

ui/drawer/src/DrawerContent.tsx, ui/drawer/src/play.stories.tsx
This PR expands the accepted values of the `width` and `height` attributes of the drawer to include `auto` as a value. Allowing the Drawer to dynamically resize based on its content.
SRED-418
=> feat: add `auto` as valid value for Drawer height and width

build.washingtonpost.com/components/Markdown/Components/Sandbox.js, build.washingtonpost.com/pages/playroom.js
adds "save" aka a one way sync to the search params for code in playroom pages
=> chore: add save feature to full playroom pages

ui/carousel/src/CarouselContent.tsx
i had warnings in my console to add a key so I added one here, i don't think there are any issues with keys and clone elements.
=> fix: adding key to cloned carousel items

build.washingtonpost.com/docs/foundations/wam.mdx
The Getting started link was not working on the WAM doc because it was missing the `/` so I added it
=> fix: anchor link for getting started

ui/input-textarea/src/InputTextarea.tsx
This PR fixes the overlap of label and content in the InputTextarea
SRED-553
=> fix: prevent content and label overlap in InputTextarea

ui/alert-banner/src/AlertBanner.tsx, ui/alert-banner/src/play.stories.tsx
This PR fixes the alignment the text and icons in AlertBanner
**Previous**
**Updated**
SRED-557
=> fix: correct alignment of text and icons in AlertBanner

build.washingtonpost.com/components/Layout/Components/Sidebar.js
This PR removes the duplicate Resources link in the mobile nav
SRED-566
=> fix: remove duplicate resources link in mobile nav

build.washingtonpost.com/components/ComponentPage/ComponentDetails.jsx
https://wpds-ui-kit-storybook.preview.now.washingtonpost.com/?path=/story/action-menu
=> feat: add link to storybook in component doc page

build.washingtonpost.com/components/NavigationBar.js, build.washingtonpost.com/components/ThemeToggle.js
This PR replaces the emojis in the light/dark mode toggle with WPDS icons
Before:
After:
SRED-568
=> chore: replace docs dark mode toggle sun and mood emojis with wpds icons

ui/select/src/SelectLabel.tsx, ui/select/src/SelectTrigger.tsx, ui/select/src/SelectValue.tsx, ui/select/src/play.stories.tsx
This PR truncates label text in the select component to prevent the addition of extra space and text escaping the container
=> fix: refactor select layout to deal with long label text and overflow

build.washingtonpost.com/components/Layout/Components/Sidebar.js
updated the comparison for active nav item
SRED-629
=> fix: prevent Input text from being highlighted when Input Text Area is the active page in guide

build.washingtonpost.com/package.json, build.washingtonpost.com/pages/_app.js, build.washingtonpost.com/services/getContributors.js, package-lock.json
=> feat: add snowfall to website for fun

build.washingtonpost.com/components/Markdown/Components/Checkbox.js, package-lock.json, ui/carousel/package.json, ui/carousel/src/CarouselContent.tsx, ui/carousel/src/CarouselTitle.tsx, ui/carousel/src/play.stories.jsx, ui/input-text/package.json, ui/input-text/src/InputText.tsx, ui/input-textarea/package.json, ui/input-textarea/src/InputTextarea.tsx, ui/kitchen-sink/package.json, ui/radio-group/package.json, ui/radio-group/src/RadioGroup.tsx, ui/select/package.json, ui/select/src/SelectTrigger.tsx
This PR removes nanoid and replaces it with React 18's native `useId` 
SRED-384
=> feat: remove nanoid dependency

ui/input-text/src/InputText.tsx
This PR removes the border from clear button in search fields.
It appears that `css` props for elements that are conditionally rendered to no work as expected in Next
SRED-473
=> fix: remove border for clear button on input search

ui/theme/src/wpds.tokens.json
Reverted subtle and faint tokens to their original values. Added a description to flag them as legacy and subject to depreciated
=> fix: reverted subtle and faint tokens

packages/kit/src/select/SelectTrigger.tsx
This PR adds back in a missing 180 transform to the Select's chevron icon when open
=> fix: transform Select arrow on open

packages/kit/src/error-message/ErrorMessage.tsx, packages/kit/src/helper-text/HelperText.tsx
This PR changes the HelperText and ErrorMessage elements to be block-level elements so their line height is always consistent
=> fix: make input helper and error block level elements to preserve formatting

ui/error-message/src/ErrorMessage.tsx, ui/helper-text/src/HelperText.tsx
This PR changes the HelperText and ErrorMessage elements to be block-level elements so their line height is always consistent
=> fix: make input helper and error text block level elements for consistent formatting

.prettierignore, tsconfig.json, ui/theme/src/stitches.config.ts
This PR increases the specificity of the wpds-dark selector to a strength of 020 by using a multiple class selector that is a duplicate of itself, allowing the class attribute to remain the same.
This ensures that the dark theme custom properties override light theme, even when light the theme properties are rewritten into the dom by dynamically loaded components.   
```
.wpds-dark.wpds-dark {
--wpds-colors-gray700: rgba(...)
...
}
...
<html class="wpds-dark">
```
=> feat: increase the specificity of the wpds-dark selector to ensure it overrides light variables

build.washingtonpost.com/components/Markdown/Components/Checkbox.js, package-lock.json, packages/kit/package.json, packages/kit/src/carousel/CarouselContent.tsx, packages/kit/src/carousel/CarouselTitle.tsx, packages/kit/src/input-text/InputText.tsx, packages/kit/src/input-textarea/InputTextarea.tsx, packages/kit/src/radio-group/RadioGroup.tsx, packages/kit/src/select/SelectTrigger.tsx
https://arcpublishing.atlassian.net/browse/R18-114
- We would eventually like to use React.useId again
=> fix: add nanoid back

build.washingtonpost.com/components/NavigationBar.js
sister pr https://github.com/washingtonpost/wpds-ui-kit/pull/608
1. Visit https://wpds-ui-kit-git-switcherrr.preview.now.washingtonpost.com/.
2. View switch component in top right of navigation bar
3. Tapping it should navigate you to the v2 docs site domain.
=> feat: add v2 docs switcher

packages/kit/package.json
I noticed an issue with updating a reference in furniture EHF to use kit tokens file. 
> [commonjs--resolver] Missing "./src/theme/tokens" specifier in "@washingtonpost/wpds-ui-kit" package
=> fix: add tokens specifier to exports

ui/tokens/scripts/build.mjs
This removes the global styles from wpds-tokens. We want that package to contain only tokens, or else a user cannot import it without getting the global styles added to their application as well (Spaces ran into this issue).
This thread has more context: https://washpost.slack.com/archives/C01FWHF12BG/p1711660089255659
Ticket: https://arcpublishing.atlassian.net/browse/CRX-1227
=> fix: remove global styles from wpds-tokens

build.washingtonpost.com/next.config.js
my local builds weren't working, showing errors like this.
```
@washingtonpost/wpds-docs:build: ../packages/kit/dist/esm/index.js
@washingtonpost/wpds-docs:build: Module not found: Can't resolve './chunk-RWSJFR6A.js'
@washingtonpost/wpds-docs:build: 
@washingtonpost/wpds-docs:build: https://nextjs.org/docs/messages/module-not-found
@washingtonpost/wpds-docs:build: 
@washingtonpost/wpds-docs:build: Import trace for requested module:
@washingtonpost/wpds-docs:build: ./components/Markdown/Examples/HexRGBAColorSamples.jsx
@washingtonpost/wpds-docs:build: ./components/Markdown/Styling.js
@washingtonpost/wpds-docs:build: ./pages/playroom.js
```
=> chore: the builds were breaking with these options added

packages/kit/src/input-search/InputSearchInput.test.tsx, packages/kit/src/input-search/InputSearchInput.tsx, packages/kit/src/input-search/play.stories.tsx
update with tempText when value is passed to InputSearch
=> fix: allow controlled InputSearch to update onChange handler with temp text value

packages/kit/src/theme/wpds.tokens.json
Change dark mode color value for Hex and RGB
Current Hex: #F02E41
Change Hex to: #FF3636
=> fix: update dark mode color Red100 to new value [STRY-567]

packages/kit/src/input-search/InputSearchInput.tsx, packages/kit/src/input-search/InputSearchRoot.tsx, packages/kit/src/input-search/play.stories.tsx
This PR slightly refactors input search to better respond to keyboard interaction and edits to selected text, as well as adding an interaction test story to validate
Steps to test
1. Start searching
2. Key down to one of the autocomplete suggestions
3. Try making a change to the autocomplete result in the search bar by backspacing or typing more letters
4. Changes **are** made as expected
5. Clear the search bar by clicking the x icon, it clears as expected
STRY-679
=> fix: prevent frozen InputSearch after text editing

build.washingtonpost.com/components/ComponentPage/ComponentDetails.jsx
The GitHub link to each component's source code goes to the wrong directory.
For example, the source code for the [Box]() component goes to the [old `ui` directory](https://github.com/washingtonpost/wpds-ui-kit/tree/main/ui/box) when it should go to the [new `packages/kit/src`directory](https://github.com/washingtonpost/wpds-ui-kit/tree/main/packages/kit/src/box)
Point all component GitHub links to the correct directory within the repository.
=> fix: update component github links on build site

build.washingtonpost.com/package.json, package-lock.json, package.json, packages/eslint-plugin/package.json, packages/kit/package.json, packages/kitchen-sink/package.json, packages/tailwind-theme/package.json, packages/tokens/package.json
updates the washingtonpost logo https://github.com/washingtonpost/wpds-assets-manager/pull/220/files#diff-c40429ccb8bf629122e52f1105ff8c28653a7cb36c337d238c6f63450e8a3b36 
test page
https://wpds-ui-kit-git-bump-kit.preview.now.washingtonpost.com/foundations/logos
scroll to washingtonpost logo (first one) 
toggle theme - logo color should switch back and forth
=> feat: update wpds-assets

build.washingtonpost.com/components/Markdown/Examples/IconSamples.jsx, build.washingtonpost.com/docs/components/input-search.mdx, packages/kit/src/input-search/InputSearchInput.tsx, packages/kit/src/input-search/InputSearchListItem.tsx, packages/kit/src/input-search/InputSearchRoot.tsx, packages/kit/src/input-search/play.stories.tsx
This PR consolidates several fixes to InputSearch that have been reported over the past few weeks
1. CFE-296 To sanitize input and prevent a regular expression error
Enter ( in the [input](https://wpds-ui-kit-storybook-git-input-search-fixes.preview.now.washingtonpost.com/?path=/story/inputsearch--play) and not get JS errors
3. CFE-344 Externally clearing when the input is controlled
clear input text in [controlled example](https://wpds-ui-kit-storybook-git-input-search-fixes.preview.now.washingtonpost.com/?path=/story/inputsearch--controlled) with external button
4. CFE-345 To honor the `disabled` prop in list items
new [disabled story](https://wpds-ui-kit-storybook-git-input-search-fixes.preview.now.washingtonpost.com/?path=/story/inputsearch--disabled)
5. CFE-346 To honor the `css` …
=> Input search fixes

build.washingtonpost.com/components/next-seo/defaultSeo.tsx
Added `noindex,nofollow` to robots meta tag for non-production pages to avoid having preview/non-prod pages picked up search engines.
- Go to [build page](https://wpds-ui-kit-git-cfe-356-robots-metatag.preview.now.washingtonpost.com/)
- Confirm you see `noindex,nofollow` in robots meta tag
=> fix: update robots meta tag in non prod builds

build.washingtonpost.com/components/Markdown/Examples/Breakpoints.jsx, packages/kit/src/input-search/InputSearchInput.tsx, packages/kit/src/input-search/InputSearchRoot.tsx, packages/kit/src/input-search/play.stories.tsx
This PR  adds code to handle a mismatch of internal and external state when a controlled input is cleared.
In addition, it updates how clearing is handled to ensure onSelect is called.
=> fix: allow for reselecting the last selection of InputSearch if cleared. Trigger InputSearch onSelect callback when selection is cleared.

package-lock.json
Updating `package-lock.json` with the latest `@washingtonpost/site-footer` version `1.6.8`.
1. Visit https://wpds-ui-kit-git-fix-footer-fouc.preview.now.washingtonpost.com/ and verify footer no longer has gaps and FOUC
=> chore: bump @washingtonpost/site-footer version

.storybook/preview.js
Noticed that it gets super annoying to test (or even look at) our components in mobile break points because of the split light/dark. Changed it so that now on small breakpoints the light/dark containers are stacked instead of next to each other.
Before (@sm breakpoint only)
After (@sm breakpoint only)
=> chore: stack examples at sm breakpoints

package-lock.json, packages/kit/package.json, packages/kit/src/dialog/play.stories.tsx
Bumped up radix dialog version
added extra storybook example
Check that you can see the pseudo states in select inside the dialog.
https://wpds-ui-kit-storybook-git-fix-select-ps-dialog.preview.now.washingtonpost.com/?path=/story/dialog--complex
https://wpds-docs-git-fix-select-ps-dialog.preview.now.washingtonpost.com/components/dialog
https://arcpublishing.atlassian.net/browse/WE-70
=> chore: fix pseudo states not working inside dialog [WE-70]

build.washingtonpost.com/components/Search/SearchInput.jsx
1. https://wpds-docs-git-cmd-k.preview.now.washingtonpost.com/
2. Tap CMD + K
3. Search dialog should open
=> adds cmd k shortcut to doc search
