.github/dependabot.yml
plop-templates/component/package.json.hbs
ui/alert-banner/package.json
ui/app-bar/package.json
ui/box/package.json
ui/button/package.json
ui/checkbox/package.json
ui/container/package.json
ui/icon/package.json
ui/kit/package.json
ui/theme/package.json
ui/visually-hidden/package.json

chore: use washingtonpost org

---

ui/theme/src/stitches.config.ts

`Stitches.PropertyValue<T>` for `my` and `mx` should be "margin"

fix: change Stitches.PropertyValue type to "margin"

---

ui/input-textarea/README.md
ui/kit/package.json

This PR adds missing dependencies to ui-kit package and updates textarea readme with proper component name

Export issues

---

CHANGELOG.md

docs: changelog edits

---

.storybook/main.js
app/package.json
app/pages/index.tsx
package-lock.json
package.json
ui/button/src/play.spec.ts
ui/fieldset/README.md
ui/fieldset/package.json
ui/fieldset/src/Fieldset.tsx
ui/fieldset/src/index.ts
ui/fieldset/src/play.stories.jsx
ui/kit/package.json
ui/kit/src/index.ts
ui/radio-group/README.md
ui/radio-group/package.json
ui/radio-group/src/RadioButton.tsx
ui/radio-group/src/RadioGroup.tsx
ui/radio-group/src/index.ts
ui/radio-group/src/play.stories.jsx

This PR adds a new RadioGroup component with RadioButton and Fieldset sub components

feat: add RadioGroup component

---

docs/RELEASING.md

docs: add releasing doc from notion

---

.storybook/main.js
.storybook/preview.js

With Art, we added a side-by-side light and dark mode view to storybook and removed the theme toggle, making it quicker and easier to visually test components in dark mode.

Dark mode panel storybook

---

.storybook/preview.js
ui/button/src/play.stories.jsx
ui/visually-hidden/src/play.stories.jsx

Add new props to decorators in order to use in interaction tests so they don't fail.

chore: fix chromatic tests

---

docs/architecture/000-architecture-decision-records.md
docs/architecture/001-branching-strategy.md

This PR proposes a new branching strategy for UI Kit

feat: add new architecture section to docs and initial ADR for branching

---

ui/input-shared/src/InputShared.tsx
ui/input-text/src/play.stories.jsx

This PR fixes a reported bug https://arcpublishing.atlassian.net/browse/MED-4450 that programatic changes to input value value did not cause the label to float

fix: float label on controlled input value changes

---

build.washingtonpost.com/components/Footer.js
build.washingtonpost.com/pages/release-notes/index.js

docs: update github repo references to wpds-docs

---

build.washingtonpost.com/components/NavigationBar.js
build.washingtonpost.com/services/getDocByPathName.js
build.washingtonpost.com/services/getDocsListBySection.js
build.washingtonpost.com/services/getNavigation.js
build.washingtonpost.com/services/getPackageData.js
build.washingtonpost.com/services/getPropsTable.js

resolves issue found with hot loading with mdx files

docs: remove cache from getdocbypathname

---

build.washingtonpost.com/docs/foundations/size.mdx

fix(docs): fix sizes typo

---

ui/icon/src/icon.tsx

- use size util
- add css override prop

feat: add size util and css prop to icon component

---

build.washingtonpost.com/components/ComponentPage/ComponentDetails.jsx
build.washingtonpost.com/pages/components/[slug].js

- pull component details into a doc component file
- encourage use of ui-kit import and pkg

fix: encourage use of ui-kit import and pkg

---

.github/workflows/latest-release.yml
Makefile

- update lock file after release

chore: update lock file after release

---

build.washingtonpost.com/package.json
package-lock.json

docs: add next-remote-watch for hotreloading mdx files

---

package-lock.json
ui/input-text/src/InputText.tsx
ui/input-text/src/StyledContainer.tsx
ui/input-text/src/play.stories.jsx

add a css override prop for the styled container component

fix: add styles override to input text  container

---

docs/architecture/002-extra-small-breakpoint.md

Creates an ADR proposing a new extra small breakpoint

ADR: Add an Extra Small Breakpoint

---

build.washingtonpost.com/public/sitemap.xml
package-lock.json
ui/kit/package.json

This PR updates the index file in ui-kit to ensure that Select is a dependency

Index update

---

build.washingtonpost.com/components/Typography/link.js
build.washingtonpost.com/pages/404.js
build.washingtonpost.com/public/sitemap.xml

add custom 404, open algolia modal when search link is clicked

feat: add custom 404 page

---

build.washingtonpost.com/pages/404.js

fix: add sidenav to 404

---

ui/input-text/src/InputText.tsx
ui/input-text/src/play.stories.jsx
ui/input-textarea/src/InputTextarea.tsx

Added placeholder text to the list of `isFloating` conditions

fix: float input label when placeholder text is present

---

build.washingtonpost.com/docs/components/checkbox.mdx
package-lock.json
ui/checkbox/package.json
ui/checkbox/src/Checkbox.tsx
ui/checkbox/src/play.stories.jsx
ui/input-label/package.json
ui/input-label/src/InputLabel.tsx
ui/input-shared/src/InputShared.tsx

Added required stylings for checkbox
Before:
After:

fix: add asterisk to required checkbox to match input required styles

---

build.washingtonpost.com/docs/components/select.mdx

fix typo in select component docs site

chore: update select description

---

package-lock.json
ui/tooltip/src/play.stories.tsx
ui/visually-hidden/src/play.stories.tsx

Migrate t and v component stories to tsx

Chore: migrate t and v to tsx

---

build.washingtonpost.com/next.config.js
build.washingtonpost.com/vercel.json
vercel.json

fix: add redirect for storybook for our build site

---

ui/divider/src/play.stories.tsx
ui/drawer/src/DrawerRoot.tsx
ui/drawer/src/play.stories.tsx
ui/error-message/src/play.stories.tsx
ui/fieldset/src/play.stories.tsx
ui/helper-text/src/play.stories.tsx

chore: migrate to tsx divider, drawer, error message, fieldset, and helper text

---

ui/pagination-dots/src/play.stories.tsx
ui/popover/src/play.stories.tsx
ui/radio-group/src/play.stories.tsx
ui/scrim/src/play.stories.tsx

chore: migrate stories to TSX - p2r

---

build.washingtonpost.com/components/ComponentPage/ComponentStatus.jsx
build.washingtonpost.com/components/Layout/Components/Sidebar.js
build.washingtonpost.com/components/Markdown/Styling.js
build.washingtonpost.com/docs/components/accordion.mdx
build.washingtonpost.com/docs/components/avatar.mdx
build.washingtonpost.com/docs/components/card.mdx
build.washingtonpost.com/docs/components/divider.mdx
build.washingtonpost.com/docs/components/drawer.mdx
build.washingtonpost.com/docs/components/input-password.mdx
build.washingtonpost.com/docs/components/input-text.mdx
build.washingtonpost.com/docs/components/input-textarea.mdx
build.washingtonpost.com/docs/components/pagination-dots.mdx
build.washingtonpost.com/docs/components/popover.mdx
build.washingtonpost.com/docs/components/radio-group.mdx
build.washingtonpost.com/docs/components/select.mdx
build.washingtonpost.com/docs/components/tooltip.mdx
build.washingtonpost.com/docs/support/component-status.mdx
build.washingtonpost.com/pages/components/[slug].js
build.washingtonpost.com/public/sitemap.xml

This PR removes the `Draft` status from components using it. It adds the new `Beta` status and a page explaining the statuses.

Component status

---

build.washingtonpost.com/pages/_app.js
build.washingtonpost.com/pages/_document.js

feat: update gtm implementation
https://arcpublishing.atlassian.net/browse/WPDS-1322

feat: update gtm implementation

---

build.washingtonpost.com/docs/components/box.mdx
build.washingtonpost.com/public/sitemap.xml
build.washingtonpost.com/services/getPropsTable.js
ui/box/src/box.tsx

docs: box page
https://wpds-ui-kit-git-box-doc.preview.now.washingtonpost.com/components/box

docs: box page

---

build.washingtonpost.com/docs/components/checkbox.mdx
ui/checkbox/README.md
ui/checkbox/src/Checkbox.tsx

Adds an example on the Checkbox docs for how to write custom labels

chore: update checkbox docs

---

ui/icon/src/icon.tsx

fix: fix icon fill

---

build.washingtonpost.com/pages/playroom.js

chore: add caching to playroom route

---

.github/workflows/latest-release.yml

chore: update git autocommit release action step w/ env variables

---

.github/workflows/chromatic-prod.yml
.github/workflows/experimental-release.yml
.github/workflows/interaction-tests.yml
.github/workflows/latest-release.yml
.github/workflows/playwright.yml
.github/workflows/validation.yml
ui/button/README.md

I added remote caching following this guide. https://turbo.build/repo/docs/ci/github-actions

chore: add turbo repo remote caching

---

build.washingtonpost.com/docs/resources/guides/tachyons-stitches.mdx
build.washingtonpost.com/docs/resources/tools/tachyons-to-stitches.mdx
build.washingtonpost.com/pages/resources/[category]/index.js

I want to access the tachyons to stitches converted on the site

fix: update code to get the tools link working

---

ui/button/src/Button.tsx

fix: button density set to default value

---

build.washingtonpost.com/pages/resources/[category]/index.js

fix: lint errors

---

build.washingtonpost.com/components/Markdown/Examples/LogoSamples.jsx
build.washingtonpost.com/package.json
package-lock.json

bump the wam import in the doc site and add the logo names to the logo names list.

chore: add helpdesk logos to docs site

---

Makefile
package-lock.json
ui/input-label/src/InputLabel.tsx
ui/input-shared/src/InputShared.tsx
ui/input-text/src/InputText.tsx
ui/input-text/src/play.stories.tsx
ui/input-textarea/src/InputTextarea.tsx

[SRED-145](https://arcpublishing.atlassian.net/jira/software/c/projects/SRED/boards/1185?modal=detail&selectedIssue=SRED-145)
[SRED-145]: https://arcpublishing.atlassian.net/browse/SRED-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add cancel button to input type search

---

build.washingtonpost.com/docs/components/carousel.mdx

docs: carousel doc typos and spacing

---

build.washingtonpost.com/components/logo.js
build.washingtonpost.com/package.json
package-lock.json

chore: bump build to wam@1.20.0

---

ui/tailwind-theme/package.json

This PR changes the package.json for the tailwind theme to make it public

feat: make tailwind theme package public

---

ui/input-search/src/InputSearchInput.tsx
ui/input-search/src/InputSearchList.tsx
ui/input-search/src/InputSearchListItem.tsx
ui/input-search/src/InputSearchPopover.tsx
ui/input-search/src/InputSearchRoot.tsx
ui/input-search/src/play.stories.tsx

This PR updates the types for the InputSearch components to surface the full api for TypeScript

fix: updated InputSearch sub component types

---

ui/theme/src/tokens.ts

This PR adds includes a necessary built file to the theme package

chore(theme): build tokens into .ts file

---

build.washingtonpost.com/docs/support/supported-platforms.mdx

docs: Update supported-platforms.mdx

---

build.washingtonpost.com/docs/components/coach-marks.mdx

docs: coach marks stub

---

build.washingtonpost.com/docs/resources/guides/performance-and-seo.mdx

The guide is a little hard to read without some styling changes. Now that the lists are unpacked, I use Markdown level 3 headers for the sub-sub-headers, and sections that start with a colon clause are now made bold. It makes it easier to read.
I also fixed a broken link to Yoast.

no numbered lists except resources and consistent header stylings

---

ui/action-menu/src/ActionMenu.tsx
ui/action-menu/src/ActionMenuIcon.tsx
ui/action-menu/src/play.stories.tsx

Replace LeftIcon and RightIcon as implemented in play.stories.tsx with a new reusable component ActionMenuIcon

Add ActionMenuIcon component

---

.npmrc
package-lock.json

add npmrc back

---

build.washingtonpost.com/package.json
package-lock.json

chore: bump wam in build site

---

package-lock.json
ui/kit/package.json
ui/kit/src/index.ts

chore: add action menu to kit pkg

---

Makefile

fix: add no push flag on publish action

---

Makefile

fix: remove no push flags from publish and version

---

build.washingtonpost.com/docs/foundations/wam.mdx

updating yotuube embed component props

fix: updating embed code SRED-369

---

build.washingtonpost.com/docs/components/switch.mdx

feat: move switch to stable

---

ui/theme/src/token-structure.md

Created a relationship graph to outline our current token logic.
Motivation:
Needed a relationship graph that will help explain the updates to the tokens after our dark mode color update. This would include mapping theme tokens to different tier 1 (context) tokens depending on the context i.e. light or dark. etc

doc: created-token-structure-markdown

---

build.washingtonpost.com/components/Layout/Components/Sidebar.js

feat: adding Support to sidebar nav

---

docs/CONTRIBUTING.md
ui/kitchen-sink/src/KitchenSink.tsx
ui/select/src/SelectLabel.tsx

Use has and a data-value attribute to float the label

fix: Floating select label SRED-446

---

Makefile
package.json

Throw CI error if there are formatting and/or linting errors

chore: add format check to validation action

---

ui/input-text/src/InputText.tsx

fix: input text event issue

---

build.washingtonpost.com/components/Footer.js

Added the links, let me know if design and code is acceptable. Tried not to spend too much time on it. 
Scroll to bottom to see the links: 
https://wpds-ui-kit-git-feat-add-links.preview.now.washingtonpost.com/

feat: add links to build site [SRED-199]

---

.storybook/preview.js
build.washingtonpost.com/components/ComponentPage/ComponentStatus.jsx
build.washingtonpost.com/components/Footer.js
ui/carousel/src/CarouselContent.tsx
ui/carousel/src/CarouselItem.tsx
ui/carousel/src/play.stories.jsx
ui/carousel/src/useActiveDescendant.test.tsx
ui/carousel/src/useActiveDescendant.ts
ui/input-text/src/InputText.tsx

This PR updates the focus logic in Carousel to better handle the clicking of buttons as child elements of `Carouseltem` s

Carousel focus

---

build.washingtonpost.com/package.json
build.washingtonpost.com/pages/_app.js
package-lock.json
ui/tokens/README.md

docs: update docs on tokens pkg

---

build.washingtonpost.com/docs/resources/tutorials/carousel.mdx

https://arcpublishing.atlassian.net/browse/SRED-550
Reformatted any instance where code formatting was not taking place

docs: SRED-550:Carousel Guide Fix

---

.github/workflows/chromatic-prod.yml
.github/workflows/validation.yml

feat: add onlyChanged to chromatic tests

---

build.washingtonpost.com/components/ComponentPage/ComponentStatus.jsx
build.washingtonpost.com/components/Markdown/Styling.js
build.washingtonpost.com/components/Typography/Description.js
build.washingtonpost.com/pages/components/[slug].js
build.washingtonpost.com/pages/foundations/[slug].js
build.washingtonpost.com/pages/resources/index.js
build.washingtonpost.com/pages/support/[slug].js
build.washingtonpost.com/pages/support/index.js
build.washingtonpost.com/pages/zzz/[slug].js

This PR sets a new more readable width on text for WPDS docs
SRED-567

fix: set max width on paragraphs

---

.gitignore
build.washingtonpost.com/package.json
package-lock.json
package.json

feat: bump wam to 1.24.0

---

build.washingtonpost.com/package.json
package-lock.json
package.json
ui/box/package.json

fix: our lockfile area for build dot site was borked

---

package-lock.json
ui/input-label/package.json
ui/input-label/src/InputLabel.tsx

Bump Radix label to 2.x 
SRED-319

feat: updated InputLabel with latest Radix label component

---

package-lock.json
ui/accordion/package.json
ui/kitchen-sink/src/KitchenSink.tsx

Bumped Radix accordion version and ensured it would build into apps without errors
SRED-383

fix: take latest minor of Radix accordion

---

build.washingtonpost.com/components/Footer.js
build.washingtonpost.com/package.json
package-lock.json

feat: add site footer back

---

ui/theme/src/stitches.config.ts

SRED-649
related pr https://github.com/WashPost/wpds-site-furniture/pull/2426

fix: fixes a scrollbar issue with select and our header component

---

package-lock.json

feat: fresh install with updated node/npm

---

build.washingtonpost.com/components/Markdown/Examples/ThemeTokens.jsx
ui/theme/src/wpds.tokens.json

After much reflection and thought about the modifier forCards. I wanted to align more clearly to the tokens surface. To make it as clear as possible that its intention is to be used with surfaces

fix: Change forCards modifier to forSurfaces

---

.prettierignore
Makefile
ui/kit/README.md

fix: formatting changes

---

ui/theme/src/stitches.config.ts

update toString call and className access to ensure that the underlying method call happens

fix: ensure that dark theme colors get written into the dom

---

apps/nextjs13-approuter/package.json
apps/nextjs13-pagerouter/package.json
apps/nextjs14-approuter/package.json
apps/nextjs14-pagerouter/package.json
apps/nextjs14-pagerouter/src/pages/index.jsx
build.washingtonpost.com/next.config.js
build.washingtonpost.com/package.json
package-lock.json
package.json
packages/kit/package.json
packages/kit/tsup.config.ts
packages/kitchen-sink/package.json
packages/tokens/scripts/build.mjs
templates/component-with-subcomponents/package.json.hbs
templates/component/package.json.hbs
tsconfig.base.json

Add new treeshake option to kit. i followed this helpful blog post https://dorshinar.me/posts/treeshaking-with-tsup

feat: use treeshaking from tsup

---

apps/nextjs13-approuter/package.json
apps/nextjs13-pagerouter/package.json
apps/nextjs14-approuter/package.json
apps/nextjs14-pagerouter/package.json
build.washingtonpost.com/next.config.js
build.washingtonpost.com/package.json
jsconfig.json
package-lock.json
packages/kit/package.json
packages/kit/src/select/Select.ts
packages/kit/src/select/SelectContent.tsx
packages/kit/src/select/SelectLabel.tsx
packages/kit/src/select/SelectRoot.tsx
packages/kit/src/select/SelectTrigger.tsx
packages/kit/src/select/SelectValue.tsx
packages/kit/src/select/index.ts
packages/kitchen-sink/package.json
packages/kitchen-sink/src/KitchenSink.tsx
packages/tokens/package.json
packages/tokens/scripts/build.js

fix: fix build issue with tokens & front-end test apps

---

package-lock.json
package.json
packages/kit/package.json

I got an error when trying to update furniture to latest ui-kit here:
https://github.com/WashPost/wpds-site-furniture/pull/2521

feat: add tokens to export config

---

packages/kit/src/navigation-menu/NavigationMenuLink.tsx

fix: remove extra css color for data-active style in nav menu link

---

build.washingtonpost.com/package.json
package-lock.json
package.json
packages/kit/package.json
packages/kitchen-sink/package.json
packages/tokens/package.json

feat: update wam

---

build.washingtonpost.com/components/Markdown/Examples/TokenColorTable.jsx

fix: color search bug

---

packages/kit/src/input-search/play.stories.tsx

chore: update select function

---

build.washingtonpost.com/docs/foundations/color.mdx
packages/kit/src/scrim/Scrim.tsx

Refactored Scrim to make lockScroll work again

fix: make lockScroll property work

---

build.washingtonpost.com/components/Markdown/Examples/IconSamples.jsx
packages/kit/src/navigation-menu/NavigationMenuTrigger.tsx
packages/kit/src/navigation-menu/play.stories.tsx

This PR fixes the lack of text styling when a `NavigationMenu.Trigger` is marked `disabled`
CFE-277

Nav menu trigger fix

---

build.washingtonpost.com/components/Markdown/Examples/LogoSamples.jsx
package-lock.json
package.json
packages/kit/package.json
packages/kitchen-sink/package.json
packages/tokens/package.json

chore: update wam on docs site

---

build.washingtonpost.com/components/Markdown/Components/StyleConverter.js
packages/kit/src/drawer/DrawerContent.tsx

fix: prettify
